In [2]:
import pandas as pd
from sodapy import Socrata

In [24]:
client = Socrata("data.cityofchicago.org",
                "6zCezNDBAnGipsgCJcJHdJ6Yr",
                "consimike@gmail.com",
                  "BlahBlah1")
results = client.get("spqx-js37", limit=1000)

results_df = pd.DataFrame.from_records(results)
results_df.head()

,:@computed_region_43wa_7qmu,:@computed_region_6mkv_f3dw,:@computed_region_awaf_s7ux,:@computed_region_bdys_3d7i,:@computed_region_vrxf_vc4k,address,camera_id,intersection,latitude,location,longitude,violation_date,violations,x_coordinate,y_coordinate
0,22,21861,45,663,74,11100 S HALSTED ST,2422,111TH AND HALSTED,41.692263123,"{'latitude': '41.692263123425136', 'longitude'...",-87.642522688,2019-06-10T00:00:00.000,8,1172923.657689312,1831209.044179248
1,22,21861,45,642,50,800 W 119TH STREET,2404,119TH AND HALSTED,41.677923389,"{'latitude': '41.677923389134385', 'longitude'...",-87.641989646,2019-06-10T00:00:00.000,1,1173111.174088158,1825985.001014405
2,22,21861,45,662,50,11900 S HALSTED,2402,119TH AND HALSTED,41.677720829,"{'latitude': '41.67772082924762', 'longitude':...",-87.642051845,2019-06-10T00:00:00.000,6,1173094.774616191,1825911.054609338
3,10,21194,1,560,1,400 E 31ST STREET,2123,31ST ST AND MARTIN LUTHER KING DRIVE,41.838534018,"{'latitude': '41.838534018118914', 'longitude'...",-87.617046113,2019-06-10T00:00:00.000,4,1179437.985396417,1884565.84226022
4,NaN,NaN,NaN,NaN,NaN,3100 S DR MARTIN L KING,2121,31ST ST AND MARTIN LUTHER KING DRIVE,NaN,NaN,NaN,2019-06-10T00:00:00.000,5,NaN,NaN

In [25]:
camera_group = results_df.groupby('camera_id')

In [26]:
camera_group.count()

,:@computed_region_43wa_7qmu,:@computed_region_6mkv_f3dw,:@computed_region_awaf_s7ux,:@computed_region_bdys_3d7i,:@computed_region_vrxf_vc4k,address,intersection,latitude,location,longitude,violation_date,violations,x_coordinate,y_coordinate
camera_id,,,,,,,,,,,,,,
1002,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1003,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1011,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1014,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1023,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1024,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1031,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1034,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1041,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1042,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1051,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1052,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1072,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1074,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1091,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1093,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1102,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1104,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1111,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1113,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1122,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1123,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1132,2,2,2,2,2,2,2,2,2,2,2,2,2,2
1134,3,3,3,3,3,3,3,3,3,3,3,3,3,3
1142,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1143,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1151,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1153,0,0,0,0,0,4,4,0,0,0,4,4,0,0
1161,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1163,4,4,4,4,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2541,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2543,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2571,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2581,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2582,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2621,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2624,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2631,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2632,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2651,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2654,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2672,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2674,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2701,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2702,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2714,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2721,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2731,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2763,0,0,0,0,0,4,4,0,0,0,4,4,0,0
2764,0,0,0,0,0,4,4,0,0,0,4,4,0,0
3002,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3003,4,4,4,4,4,4,4,4,4,4,4,4,4,4
3022,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3032,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3041,4,4,4,4,4,4,4,4,4,4,4,4,4,4
3051,0,0,0,0,0,4,4,0,0,0,4,4,0,0
3052,0,0,0,0,0,4,4,0,0,0,4,4,0,0
3072,4,4,4,4,4,4,4,4,4,4,4,4,4,4
3082,3,3,3,3,3,3,3,3,3,3,3,3,3,3
3084,3,3,3,3,3,3,3,3,3,3,3,3,3,3